services:
  # Django App
  web:
    build:
      context: .
      dockerfile: DockerfileLocal
    container_name: exchange_rate_api
    command: >
      sh -c "python manage.py wait_for_db &&
                  python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./src:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  # Postgres DB
  db:
    container_name: exchange_rate_db
    image: postgres:16.4-alpine
    volumes:
      - exchange_rate_db_volume:/var/lib/postgresql/data/
      - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    environment:
      - POSTGRES_PASSWORD=${SUPER_USER_PWD}
      - SQL_DATABASE=${SQL_DATABASE}
      - SQL_USER=${SQL_USER}
      - SQL_PASSWORD=${SQL_PASSWORD}

volumes:
  exchange_rate_db_volume: