services:
  # Django App
  web:
    build:
      context: .
      dockerfile: DockerfileLocal
    container_name: exchange_rate_api_test
    command: "python manage.py test -v 2"
    env_file:
      - .env.test
    depends_on:
      - db

  # Postgres DB For test environment
  db:
    container_name: exchange_rate_db_test
    image: postgres:16.4-alpine
    volumes:
      - exchange_rate_db_volume_test:/var/lib/postgresql/data/
      - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    environment:
      - POSTGRES_PASSWORD=${SUPER_USER_PWD}
      - SQL_DATABASE=${SQL_DATABASE}
      - SQL_USER=${SQL_USER}
      - SQL_PASSWORD=${SQL_PASSWORD}

volumes:
  exchange_rate_db_volume_test: